name: Compile App

on:
  pull_request:
    branches: [main]

jobs:
   build:
     runs-on: ubuntu-latest

     steps:
       - uses: actions/checkout@v4

       - name: Setup JDK 17
         uses: actions/setup-java@v4
         with:
           distribution: 'temurin'
           java-version: 17
           cache: 'gradle'

       - name: Setup Firebase Service
         run: echo '${{ secrets.FIREBASE_SERVICE }}' > app/google-services.json

       - name: Grant execute permissions for gradle
         run: chmod +x gradlew

       - name: Run Compile
         run: ./gradlew clean assemble